### ISSUE TITLE
Why are you commented unnecessary lines?

### ISSUE THREAD

**Issue by gaal1le0** [CRodr86/TrafficLight#3]
https://github.com/CRodr86/TrafficLight/blob/ec21ad86b58091cac5ba926aa18cf12f261d75c1/src/js/index.js#L1

Please keep in mind the most important thing, you don't have to comment obviously lines, the sense of comments is giving to other developers an overview of overwhelmed functions. Please I know what the following line does:

```js
import Home from '../home.jsx'
```

Please remove all the unnecessary comments of this project, close the issue and send the assignment again via Breathcode.

**Comment by CRodr86** [comment]
The issue is solved. Thanks Manu
