### ISSUE TITLE
Why the component is called `Home`?

### ISSUE THREAD

**Issue by gaal1le0** [CRodr86/TrafficLight#4]
https://github.com/CRodr86/TrafficLight/blob/ec21ad86b58091cac5ba926aa18cf12f261d75c1/src/js/component/home.jsx#L5

I really don't understand why are you calling `Home` to a component which main functionality is to be a `TrafficLight`. Naming is one of the most important thing in development, you haven't taking care about details, you need to focus on deliver a real customer solution that fit best with MY REQUIREMENTS. 

Please change this name.

**Comment by CRodr86** [comment]
The issue is solved. Thanks Manu
